import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header/Header";
import { DarkModeProvider } from "./_context/DarkModeContext";
import { ActiveSectionContextProvider } from "./_context/ActiveSectionContext";
import DarkModeToggle from "./_components/DarkModeToggle";
import ReactQueryProvider from "./_utils/ReactQueryProvider";
import ToastProvider from "./_utils/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className="w-full overflow-x-hidden bg-gray-100 transition-all duration-300 dark:bg-darkPrimary dark:text-white">
        <ReactQueryProvider>
          <DarkModeProvider>
            <ToastProvider>
              <ActiveSectionContextProvider>
                <Header />
                {children}
                <DarkModeToggle />
              </ActiveSectionContextProvider>
            </ToastProvider>
          </DarkModeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
