import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import { DarkModeProvider } from "./_context/DarkModeContext";
import { ActiveSectionContextProvider } from "./_context/ActiveSectionContext";
import DarkModeToggle from "./_components/DarkModeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className="dark:bg-darkPrimary w-full bg-gray-100 transition-all duration-300 dark:text-white">
        <DarkModeProvider>
          <ActiveSectionContextProvider>
            <DarkModeToggle />
            <Header />
            {children}
          </ActiveSectionContextProvider>
        </DarkModeProvider>
      </body>
    </html>
  );
}
