import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import { DarkModeProvider } from "./_context/DarkModeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DarkModeProvider>
      <html lang="en">
        <body className="w-full  transition-all duration-300  dark:bg-[#050816] dark:text-white">
          <Header />
          {children}
        </body>
      </html>
    </DarkModeProvider>
  );
}
